language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install --upgrade cython
  - pip install --upgrade jnius
  - pip install -r conf/requirements.txt
  - python setup.py -q install
# command to run tests
script: nosetests